name: build/install-matrix

# Controls when the action will run.
on:
  schedule:
  - cron: '0 2 * * *' # run at 2 AM UTCÂ¬
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_install:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
          set-safe-directory: 'true'
      - name: printenv && brew install cmake scdoc autoconf automake rustup-init libtool || sudo apt update && sudo apt install rustup-init scdoc cmake -y
        run: |
          printenv && brew install cmake scdoc autoconf automake rustup-init libtool || sudo apt update && sudo apt install rustup-init scdoc cmake -y || true
      - name: make libsecp256k1.a
        run: |
          make libsecp256k1.a
      - name: make
        run: |
          sudo mkdir -p /usr/local/share/man/man1 || true
          make
          make clean
      - name: sudo make nostril
        run: |
          sudo make nostril
      - name: man nostril
        run: |
          sudo man doc/nostril.1
      - name: cargo install gnostr-bins gnostr-xq
        run: |
          cargo install gnostr-bins gnostr-xq
      - name: nostril
        run: |
          file ./nostril
          ID=$(EVENT=$(./nostril --sec $(gnostr-sha256 $(git rev-parse HEAD)) --content "gnostr-chat:topic:$(git rev-parse HEAD)" --tag gnostr-chat $(git rev-parse HEAD)) && echo $EVENT | gnostr-post-event >/dev/null; echo $EVENT | gnostr-xq .id); gnostr-fetch-by-id wss://nos.lol $(echo ${ID//\"})

      - name: make xcode || true
        run: |
          make xcode || true

      - name: make xcodebuild-list || true
        run: |
          make xcodebuild-list || true

      - name: make xcodebuild || true
        run: |
          make xcodebuild || true

      - name: make xcodebuild-install || true
        run: |
          make xcodebuild-install || true
