name: gnostr-docker

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        tag: ["latest", "slim-bullseye"]
    runs-on: ${{ matrix.os }}
    container: rust:${{ matrix.tag }}

    steps:
      - run: apt-get update && apt-get install autoconf build-essential curl cmake jq libexpat1-dev libcurl4-openssl-dev libssl-dev libtool lsb-release   git make nodejs npm pkg-config python3 python-is-python3 sudo tcl zlib1g-dev -y
      ## notice: this is a pre checkout step
      ## notice: additional operations can be done prior to checkout
      ## - run: apk update && apk add bash cmake git python3 && python3 -m ensurepip
      - run: printenv
      - run: cargo search gnostr --limit 100
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
      - run: touch ~/GITHUB_TOKEN.txt
      - run: git config --global --add safe.directory /__w/gnostr/gnostr || true
      - run: cargo install gnostr-bins
      - run: cmake .
      - run: make
      - run: gnostr --sec $(gnostr-sha256)
      - run: gnostr --sec $(gnostr-sha256 $(gnostr-weeble))
      - run: gnostr --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight))
